
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
feign:
  hystrix:
    enabled: true

spring:
  cloud:
    loadbalancer:
      retry:
        #  据说ribbon重试默认已经开启
        enabled: true

ribbon:
  #  ribbon重试超时时间
  ConnectTimeout: 60000
  #  建立连接后的超时时间
  ReadTimeout: 60000
  #  对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #  切换实例的重试次数
  MaxAutoRetriesNextServer: 1
  #  对当前实例的重试次数
  MaxAutoRetries: 1
  eureka:
    enable: false

zuul:
  #  重试必配，据说在Brixton.SR5版的spring cloud中该配置默认是true，结果在Dalston.SR1中看到的是false
  retryable: true


zuul.routes.user.path: /ZlwUser/**   #这里是映射路径
zuul.routes.user.service-id: zlead-user-server     #指定服务名称
zuul.routes.user.stripPrefix: false   #不添加路由前缀===========


zuul.routes.common.path: /common/**   #这里是映射路径
zuul.routes.common.service-id: zlead-common-service     #指定服务名称
zuul.routes.common.stripPrefix: false   #不添加路由前缀===========

zuul.routes.platformgoods.path: /ZlwGoods/**   #这里是映射路径
zuul.routes.platformgoods.service-id: zlead-platform-goods-server,zlead_good_server     #指定服务名称
zuul.routes.platformgoods.stripPrefix: false   #不添加路由前缀===========


