server:
  port: 7001

eureka:
  instance:
    prefer-ip-address: true #注册服务的ip
  client:
    register-with-eureka: true #使用Eureka注册服务
    fetch-registry: true #在本地缓存注册表
    service-url:
      defaultZone: http://localhost:8761/eureka #Eureka服务位置

spring:
  application:
    name: zlead_good_server
  main:
    allow-bean-definition-overriding: true

feign:
  hystrix:
    enabled: true